# Generated by Django 4.2.6 on 2023-10-19 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mootcourt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('event_type', models.CharField(choices=[('open', 'Open'), ('private', 'Private')], default='opened', max_length=7, verbose_name='Event Type')),
                ('announcement', models.TextField(verbose_name='Announcement')),
                ('need_telegram_channel', models.BooleanField(default=False, verbose_name='Need for TG channel')),
                ('status', models.CharField(choices=[('registration', 'Registration'), ('active', 'Active'), ('completed', 'Completed')], max_length=12, verbose_name='Creation Date')),
                ('background', models.CharField(blank=True, max_length=255, null=True, verbose_name='Background')),
                ('image', models.ImageField(blank=True, null=True, upload_to='mootkourt_images/', verbose_name='Image')),
                ('display_on_main', models.BooleanField(default=True, verbose_name='Display on main page')),
            ],
        ),
    ]
