# Generated by Django 4.2.6 on 2023-10-19 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
        ('contest', '0002_initial'),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mootcourt',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Organizer'),
        ),
        migrations.AddField(
            model_name='mootcourt',
            name='referees',
            field=models.ManyToManyField(related_name='arbiters', to=settings.AUTH_USER_MODEL, verbose_name='Referees'),
        ),
        migrations.AddField(
            model_name='mootcourt',
            name='senior_referees',
            field=models.ManyToManyField(related_name='senior_arbiters', to=settings.AUTH_USER_MODEL, verbose_name='Senior referees'),
        ),
        migrations.AddField(
            model_name='mootcourt',
            name='tags',
            field=models.ManyToManyField(blank=True, limit_choices_to={'tags__count__lt': 50}, to='service.tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='mootcourt',
            name='teams',
            field=models.ManyToManyField(to='users.team', verbose_name='Teams'),
        ),
        migrations.AddField(
            model_name='mootcourt',
            name='telegram_channel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.channel', verbose_name='Telegram Channel'),
        ),
    ]
