# Generated by Django 4.2.6 on 2023-10-25 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mootcourt',
            name='status_moot_court',
            field=models.CharField(choices=[('registration', 'Registration'), ('active', 'Active'), ('completed', 'Completed')], default=0, max_length=12, verbose_name='Moot court status'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mootcourt',
            name='status',
            field=models.CharField(default='Inactive', max_length=8, verbose_name='Status'),
        ),
    ]
