# Generated by Django 4.2.6 on 2023-10-27 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0004_mootcourt_status_moot_court_alter_mootcourt_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mootcourt',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='inactive', max_length=8, verbose_name='Status'),
        ),
    ]
