# Generated by Django 4.2.6 on 2023-10-30 11:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0005_alter_mootcourt_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mootcourt',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation Date'),
        ),
    ]
