# Generated by Django 4.2.6 on 2023-10-30 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0001_initial'),
        ('contest', '0006_alter_mootcourt_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mootcourt',
            name='tags',
            field=models.ManyToManyField(blank=True, to='guides.tag', verbose_name='Tags'),
        ),
    ]
