version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: mootcourt
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 9051124

  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db