# Generated by Django 4.2.6 on 2023-10-19 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('document_type', models.CharField(choices=[('fabula', 'Fabula'), ('reglament', 'Reglament'), ('file', 'File'), ('procedural_document', 'Procedural document'), ('result_of_mootcourt', 'Result of moot court')], max_length=25, verbose_name='Document type')),
                ('file_name', models.CharField(max_length=255, verbose_name='File name')),
                ('icon', models.FileField(upload_to='icons/', verbose_name='Icon')),
                ('file', models.FileField(upload_to='documents/', verbose_name='File')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('start_date', models.DateTimeField(verbose_name='Start')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='End')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('event_type', models.CharField(choices=[('registration', 'Registration of participants'), ('document_upload', 'Document upload'), ('online_conference', 'Online conference'), ('summarizing', 'Summarizing')], max_length=50, verbose_name='Event type')),
                ('scheduled_video_conference_url', models.URLField(blank=True, null=True, verbose_name='Videoconference')),
                ('online_stream_url', models.URLField(blank=True, null=True, verbose_name='Stream')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('date_published', models.DateTimeField(auto_now_add=True, verbose_name='Publication Date')),
                ('text', models.TextField(verbose_name='Text')),
                ('recipient', models.CharField(choices=[('organization', 'University/organization'), ('participant', 'Participant'), ('coach', 'Coach'), ('referee', 'Referee')], default='participant', max_length=15, verbose_name='Recipient')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
            ],
        ),
    ]
