# Generated by Django 4.2.6 on 2023-10-25 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantProfile',
            fields=[
            ],
            options={
                'verbose_name': 'Participant',
                'verbose_name_plural': 'Participants',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.profile',),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('organization', 'University/organization'), ('participant', 'Participant'), ('coach', 'Coach'), ('referee', 'Referee')], max_length=15, verbose_name='Role'),
        ),
    ]
