# Generated by Django 4.2.6 on 2023-10-30 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='created_at',
        ),
        migrations.AddField(
            model_name='tag',
            name='name',
            field=models.CharField(default=0, max_length=255, verbose_name='Tag'),
            preserve_default=False,
        ),
    ]
